Improved metatag usage
mcaskill/charcoal-support pull request #2
Opened 2017-05-02 21:22 UTC by dominiclord

- Alternate language listing
- Allow hooking into final metatag methods
- Configurable reCaptcha lang

2017-05-05 15:51 UTC, mcaskill requested changes

2017-05-05 15:51 UTC, mcaskill commented on src/Cms/AbstractWebTemplate.php
> +                $data = [
Let's move the array format to a separate method for easy customization:
`protected function formatAlternateTranslation()`

2017-05-05 15:51 UTC, mcaskill commented on src/Cms/AbstractWebTemplate.php
> +    // Polylingual
I propose we move these methods to a `LocaleAwareTrait` except for `AbstractWebTemplate::currentLanguage()` and `AbstractWebTemplate::currentLocale()`.

2017-05-05 15:51 UTC, mcaskill commented on src/Cms/AbstractWebTemplate.php
> +            $desc = $this->metaDescriptionFromConfig();
Is there a reason the fallback methods are called `meta*FromConfig()`?
I think ``fallbackMeta*()` would be better.

2017-05-06 21:55 UTC, dominiclord commented
Not quite sure how to implement your `formatAlternateTranslation` suggestion. Seems like a good idea though.

2017-05-08 12:43 UTC, mcaskill commented on src/Cms/LocaleAwareTrait.php
> +        $isModel    = ($context instanceof ModelInterface);
Is there ever an occasion where we wouldn't be processing a `ModelInterface`?

I defined `ContextualTemplate::contextObject()` mixin to return a model.

2017-05-11 20:24 UTC, merged